### ISSUE TITLE
Release to Maven Central?

### ISSUE THREAD

**Issue by uglycustard** [codebox/javabean-tester#3]
Hi,

Do you have any plans to release this to Maven Central?

**Comment by codebox** [comment]
I hadn't considered it, but it would make sense - I'll see what's involved and update this issue if/when it's there. Thanks for the suggestion.

**Comment by uglycustard** [comment]
I use the Sonatype OSS repository service.  Here's a guide if it helps, but I seem to recall I had to do some more googling to get it to work.  It was a bit of a pain, but once the setup is complete, it's then easy to release and use the Sonatype OSS repository to push to Maven Central.

http://jroller.com/holy/entry/releasing_a_project_to_maven

**Comment by michalharakal** [comment]
+1 for maven repo

**Comment by hazendaz** [comment]
See https://github.com/hazendaz/javabean-tester/.  It does more than the original and is being released to central.  Feel free to stop by and contribute.

**Comment by Toilal** [comment]
:+1: This repo is dead, please use and contribute on hazendaz fork :)

**Comment by hazendaz** [comment]
Hi everyone, I'm working with github to break my fork from this repo as this was indicated as no longer active 8 years ago and there are some 3k commits on the fork.  It is highly active and does quite a bit more than this original repo did.  I am likely to start efforts to repackage it away from original codebox later as that has been a source of confusion for many over the years.  Original credit will remain to @codebox for all the original efforts otherwise.  The community that has forked off hazendaz/javabean-tester will retain all that info, any issues opened will be retained, etc.  If anyone runs into items that seem to have been missed in order issues here, feel free to come contribute at hazendaz/javabean-tester.  Looking here that doesn't see to be much of a case.
